In [2]:
import numpy as np
np.ones((3,4,5)).strides

(160, 40, 8)

In [4]:
ints = np.ones(10,dtype=np.uint16)
ints

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint16)

In [6]:
floats = np.ones(10,dtype=np.float32)
floats

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [7]:
np.issubdtype(ints.dtype,np.integer)

True

In [8]:
np.issubdtype(floats.dtype,np.floating)

True

In [10]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
arr.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [17]:
arr = np.arange(15)
arr.reshape((5,-1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [19]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [2]:
import numpy as np
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [6]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [10]:
from numpy.random import randn
arr = randn(5,2)
arr

array([[ 0.08029427,  1.28151939],
       [ 3.05206816, -0.55251251],
       [ 0.05677139, -0.13116786],
       [-0.10664804, -2.67121282],
       [-0.26827312,  0.69081979]])

In [12]:
first,second,third = np.split(arr,[1,3])
first

array([[0.08029427, 1.28151939]])

In [13]:
second

array([[ 3.05206816, -0.55251251],
       [ 0.05677139, -0.13116786]])

In [14]:
third

array([[-0.10664804, -2.67121282],
       [-0.26827312,  0.69081979]])

In [18]:
arr = np.arange(6)
arr1 = arr.reshape(3,2)
arr2 = randn(3,2)
np.r_[arr1,arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-0.55710164, -1.00130603],
       [ 0.44745873,  0.87196231],
       [-1.1617729 , -0.59175272]])

In [19]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
arr2

array([[-0.55710164, -1.00130603],
       [ 0.44745873,  0.87196231],
       [-1.1617729 , -0.59175272]])

In [21]:
np.c_[np.r_[arr1,arr2],arr]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [-0.55710164, -1.00130603,  3.        ],
       [ 0.44745873,  0.87196231,  4.        ],
       [-1.1617729 , -0.59175272,  5.        ]])

In [23]:
np.c_[1:6,-10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [25]:
arr =np.arange(10)*100
arr

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [27]:
inds = [7,1,2,6]
arr[inds]

array([700, 100, 200, 600])

In [30]:
arr.put(inds,42)
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [32]:
arr.put(inds,[40,41,42,43])
arr

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

In [45]:
arr = np.random.randn(4,3)
arr

array([[ 1.08888748,  0.35027591, -1.18237462],
       [-0.63981225, -1.62782354, -0.9562792 ],
       [-0.84020757,  0.08814996,  0.39285526],
       [-0.40708749,  1.63251568, -0.49680301]])

In [46]:
demeaned = arr-arr.mean(0)
demeaned

array([[ 1.28844244,  0.2394964 , -0.62172422],
       [-0.44025729, -1.73860304, -0.39562881],
       [-0.64065261, -0.02262954,  0.95350565],
       [-0.20753253,  1.52173618,  0.06384738]])

In [49]:
arr.mean(0)

array([-0.19955496,  0.1107795 , -0.56065039])

In [5]:
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
arr_3d = arr[:,np.newaxis,:]
arr_3d

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [11]:
arr_3d.shape

(4, 1, 4)

In [13]:
arr_1d = np.random.normal(size=3)
arr_1d

array([ 0.30881934, -2.3014817 ,  0.29813888])

In [14]:
arr_1d[:,np.newaxis]

array([[ 0.30881934],
       [-2.3014817 ],
       [ 0.29813888]])

In [15]:
arr_1d[np.newaxis,:]

array([[ 0.30881934, -2.3014817 ,  0.29813888]])

In [19]:
arr = np.random.randn(3,4,5)
arr

array([[[ 1.99819441,  0.53418031, -0.09060497,  1.88577998,
         -1.27650943],
        [-0.23492957,  0.06709808,  0.04806934, -0.80619796,
         -0.35267782],
        [ 1.13388012,  0.34654947, -0.89802252, -0.04173964,
         -0.66601552],
        [-1.1501532 , -0.02744699, -0.15535717, -1.53214812,
          2.89237563]],

       [[ 0.98724656,  0.19321242,  0.289762  , -0.36131399,
          1.21457833],
        [ 0.73002122,  0.60182666, -0.4835325 ,  1.77472947,
          2.00251849],
        [-1.44057548,  0.36947938, -2.03490575,  0.11285608,
         -0.37986914],
        [ 1.06390627, -0.8967407 , -0.44375629, -2.22819263,
          0.95102703]],

       [[-0.15923208, -1.48865752, -1.31204617, -1.84755461,
          0.07893777],
        [-0.2895465 ,  0.04859217,  0.61780939, -0.58062027,
         -0.36240008],
        [ 0.00581607, -0.77013133,  1.30379181, -0.68341205,
         -0.10867451],
        [ 0.33140499,  1.32171088,  0.7121969 , -1.41680328,
         -1

In [22]:
depth_means = arr.mean(2)
depth_means

array([[ 0.61020806, -0.25572758, -0.02506962,  0.00545403],
       [ 0.46469706,  0.92511267, -0.67460299, -0.31075126],
       [-0.94571052, -0.11323306, -0.050522  , -0.18148258]])

In [24]:
demeaned = arr - depth_means[:,:,np.newaxis]
demeaned

array([[[ 1.38798635, -0.07602775, -0.70081303,  1.27557192,
         -1.88671749],
        [ 0.02079801,  0.32282567,  0.30379693, -0.55047037,
         -0.09695024],
        [ 1.15894974,  0.37161909, -0.8729529 , -0.01667002,
         -0.64094591],
        [-1.15560723, -0.03290102, -0.1608112 , -1.53760215,
          2.8869216 ]],

       [[ 0.52254949, -0.27148465, -0.17493506, -0.82601105,
          0.74988127],
        [-0.19509145, -0.32328601, -1.40864517,  0.8496168 ,
          1.07740582],
        [-0.7659725 ,  1.04408236, -1.36030277,  0.78745906,
          0.29473384],
        [ 1.37465753, -0.58598943, -0.13300503, -1.91744137,
          1.2617783 ]],

       [[ 0.78647844, -0.542947  , -0.36633564, -0.90184409,
          1.02464829],
        [-0.17631344,  0.16182523,  0.73104245, -0.46738722,
         -0.24916702],
        [ 0.05633807, -0.71960933,  1.35431381, -0.63289005,
         -0.05815251],
        [ 0.51288758,  1.50319346,  0.89367948, -1.2353207 ,
         -1

In [28]:
col = np.array([1.28,-0.42,0.44,1.6])
arr[:] = col[:,np.newaxis]
arr

array([[[ 1.28,  1.28,  1.28,  1.28,  1.28],
        [-0.42, -0.42, -0.42, -0.42, -0.42],
        [ 0.44,  0.44,  0.44,  0.44,  0.44],
        [ 1.6 ,  1.6 ,  1.6 ,  1.6 ,  1.6 ]],

       [[ 1.28,  1.28,  1.28,  1.28,  1.28],
        [-0.42, -0.42, -0.42, -0.42, -0.42],
        [ 0.44,  0.44,  0.44,  0.44,  0.44],
        [ 1.6 ,  1.6 ,  1.6 ,  1.6 ,  1.6 ]],

       [[ 1.28,  1.28,  1.28,  1.28,  1.28],
        [-0.42, -0.42, -0.42, -0.42, -0.42],
        [ 0.44,  0.44,  0.44,  0.44,  0.44],
        [ 1.6 ,  1.6 ,  1.6 ,  1.6 ,  1.6 ]]])

In [47]:
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
arr_3d = arr[:,np.newaxis,:]
arr_3d

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [51]:
arr_3d.shape

(4, 1, 4)

In [58]:
arr_1d = np.random.normal(size=3)
arr_1d

array([ 1.13284641, -0.64660782,  1.96140976])

In [59]:
arr_1d[:,np.newaxis]

array([[ 1.13284641],
       [-0.64660782],
       [ 1.96140976]])

In [60]:
arr_1d[np.newaxis,:]

array([[ 1.13284641, -0.64660782,  1.96140976]])

In [63]:
arr = np.random.randn(3,4,5)
arr

array([[[-1.35693636, -0.925414  , -0.30814747, -3.07813218,
         -1.09959792],
        [ 0.25555574, -0.37600728, -0.77575561,  0.3814013 ,
         -0.0431685 ],
        [ 0.39823014,  1.41952633, -0.16682251, -2.13395896,
         -0.08710983],
        [-0.44279485, -0.19256626,  0.89027814,  0.64154267,
         -0.71942274]],

       [[ 0.70638873,  0.19203556, -0.14976598,  0.4895385 ,
          0.05428172],
        [-0.14429455,  0.62264328, -1.11085599, -0.20398649,
          1.80471717],
        [ 0.32932146,  0.5228228 , -0.26578021,  1.34308548,
         -0.52097768],
        [ 0.11446038, -2.16450388,  2.03745815,  0.62718106,
         -1.7973196 ]],

       [[ 0.55849364, -0.94942242,  1.74847669,  0.17510788,
         -0.98918296],
        [ 0.46205003,  1.88239794, -0.17732973, -0.83516747,
         -1.1402239 ],
        [-0.42291747,  0.47068314,  1.91672466, -1.53176708,
         -1.03758059],
        [ 0.44600664,  0.7167951 , -0.21079726,  0.54931245,
          0

In [65]:
depth_means = arr.mean(2)
depth_means

array([[-1.35364559, -0.11159487, -0.11402697,  0.03540739],
       [ 0.25849571,  0.19364469,  0.28169437, -0.23654478],
       [ 0.10869457,  0.03834537, -0.12097147,  0.44676524]])

In [67]:
demeaned = arr - depth_means[:,:,np.newaxis]
demeaned.mean(2)

array([[-8.88178420e-17, -3.33066907e-17, -8.32667268e-17,
         0.00000000e+00],
       [ 2.77555756e-17, -4.44089210e-17, -4.44089210e-17,
         8.88178420e-17],
       [ 0.00000000e+00,  4.44089210e-17,  0.00000000e+00,
        -6.66133815e-17]])

In [68]:
depth_means[:,:,np.newaxis]

array([[[-1.35364559],
        [-0.11159487],
        [-0.11402697],
        [ 0.03540739]],

       [[ 0.25849571],
        [ 0.19364469],
        [ 0.28169437],
        [-0.23654478]],

       [[ 0.10869457],
        [ 0.03834537],
        [-0.12097147],
        [ 0.44676524]]])

In [5]:
arr = np.zeros((4,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [72]:
arr[:]=5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [75]:
col = np.array([1.28,-0.42,0.44,1.6])
arr[:]=col[:,np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [77]:
arr[:2]=[[-1.37],[0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

In [97]:
arr = np.random.randn(5,5)
arr

array([[ 1.34029268, -0.23100865,  1.0285253 , -2.3997198 ,  0.14096748],
       [ 0.71498021,  0.85084439, -1.17389892,  0.12492129,  1.0607118 ],
       [ 0.02164417, -1.08576321, -0.79213907,  0.21157638, -1.46285876],
       [ 0.51098713,  0.6137559 ,  0.30547653,  0.91054283,  1.91162077],
       [ 1.97302557, -0.42650775, -0.76913446, -0.91774665,  0.60317258]])

In [98]:
arr[::2]

array([[ 1.34029268, -0.23100865,  1.0285253 , -2.3997198 ,  0.14096748],
       [ 0.02164417, -1.08576321, -0.79213907,  0.21157638, -1.46285876],
       [ 1.97302557, -0.42650775, -0.76913446, -0.91774665,  0.60317258]])

In [99]:
arr[:,:-1] 

array([[ 1.34029268, -0.23100865,  1.0285253 , -2.3997198 ],
       [ 0.71498021,  0.85084439, -1.17389892,  0.12492129],
       [ 0.02164417, -1.08576321, -0.79213907,  0.21157638],
       [ 0.51098713,  0.6137559 ,  0.30547653,  0.91054283],
       [ 1.97302557, -0.42650775, -0.76913446, -0.91774665]])

In [100]:
arr[:,1:]

array([[-0.23100865,  1.0285253 , -2.3997198 ,  0.14096748],
       [ 0.85084439, -1.17389892,  0.12492129,  1.0607118 ],
       [-1.08576321, -0.79213907,  0.21157638, -1.46285876],
       [ 0.6137559 ,  0.30547653,  0.91054283,  1.91162077],
       [-0.42650775, -0.76913446, -0.91774665,  0.60317258]])

In [101]:
arr[:,:-1]<arr[:,1:]

array([[False,  True, False,  True],
       [ True, False,  True,  True],
       [False,  True,  True, False],
       [ True, False,  True,  True],
       [False, False, False,  True]])

In [103]:
np.all(arr[:,:-1]<arr[:,1:],axis=1)

array([False, False, False, False, False])

In [112]:
arr = np.random.randn(3,5)
arr

array([[-0.19973685,  0.40173502, -0.4209812 ,  0.18736132, -1.33943821],
       [ 0.49358868, -0.42042141, -0.01035745,  0.02275532,  0.03450783],
       [-0.30429495, -0.57593624, -0.0972534 ,  0.01133687, -2.01274055]])

In [113]:
arr[:,0].sort()
arr

array([[-0.30429495,  0.40173502, -0.4209812 ,  0.18736132, -1.33943821],
       [-0.19973685, -0.42042141, -0.01035745,  0.02275532,  0.03450783],
       [ 0.49358868, -0.57593624, -0.0972534 ,  0.01133687, -2.01274055]])

In [114]:
arr.sort()
arr

array([[-1.33943821, -0.4209812 , -0.30429495,  0.18736132,  0.40173502],
       [-0.42042141, -0.19973685, -0.01035745,  0.02275532,  0.03450783],
       [-2.01274055, -0.57593624, -0.0972534 ,  0.01133687,  0.49358868]])

In [117]:
arr.sort(axis=0)
arr

array([[-2.01274055, -0.57593624, -0.30429495,  0.01133687,  0.03450783],
       [-1.33943821, -0.4209812 , -0.0972534 ,  0.02275532,  0.40173502],
       [-0.42042141, -0.19973685, -0.01035745,  0.18736132,  0.49358868]])

In [6]:
import numpy as np
data = np.floor(np.random.uniform(0,10000,size=50))
data

array([7321., 3764., 4585., 1905., 9990., 6488., 4040., 5810., 6905.,
       3359., 7058., 6258., 8830., 5957., 3524., 9186., 3847., 5721.,
       4481., 8443., 8369., 6066., 2365., 7066., 3939., 2027., 6177.,
       3028.,  707., 8605., 4028., 8191., 5093., 4313., 7811., 9172.,
       4834.,  520., 1465., 2913., 5838.,  560., 8191., 4545.,  750.,
       8132., 9969., 8613., 3670., 4846.])

In [10]:
bins = np.array([0,100,1000,5000,10000])
labels = bins.searchsorted(data)
labels

array([4, 3, 3, 3, 4, 4, 3, 4, 4, 3, 4, 4, 4, 4, 3, 4, 3, 4, 3, 4, 4, 4,
       3, 4, 3, 3, 4, 3, 2, 4, 3, 4, 4, 3, 4, 4, 3, 2, 3, 3, 4, 2, 4, 3,
       2, 4, 4, 4, 3, 3], dtype=int64)

In [12]:
import pandas as pd
from pandas import Series,DataFrame
Series(data).groupby(labels).mean()

2     634.25
3    3573.90
4    7510.00
dtype: float64

In [15]:
x = np.random.randn(4,4)
x

array([[-0.54230051, -0.59246903, -0.42581656,  0.01824958],
       [-0.23923073,  0.14617905,  0.51349449, -1.19740926],
       [ 0.78417236,  0.4613375 , -2.08627754,  0.70782511],
       [ 0.61023423,  1.1935145 ,  0.28504693,  0.50615101]])

In [18]:
y=x[:,:1]
y

array([[-0.54230051],
       [-0.23923073],
       [ 0.78417236],
       [ 0.61023423]])

In [19]:
np.dot(y.T,np.dot(x,y))

array([[-1.42101092]])

In [21]:
xm = np.matrix(x)
xm

matrix([[-0.54230051, -0.59246903, -0.42581656,  0.01824958],
        [-0.23923073,  0.14617905,  0.51349449, -1.19740926],
        [ 0.78417236,  0.4613375 , -2.08627754,  0.70782511],
        [ 0.61023423,  1.1935145 ,  0.28504693,  0.50615101]])

In [23]:
ym = xm[:,0]
ym

matrix([[-0.54230051],
        [-0.23923073],
        [ 0.78417236],
        [ 0.61023423]])

In [24]:
ym.T*xm*ym

matrix([[-1.42101092]])

In [26]:
xm.I*x

matrix([[ 1.00000000e+00, -2.22044605e-16, -4.44089210e-16,
         -1.11022302e-16],
        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [-2.08166817e-17, -8.32667268e-17,  1.00000000e+00,
          4.85722573e-17],
        [ 0.00000000e+00, -1.11022302e-16, -8.32667268e-17,
          1.00000000e+00]])

In [27]:
np.asarray(xm.I*x)

array([[ 1.00000000e+00, -2.22044605e-16, -4.44089210e-16,
        -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-2.08166817e-17, -8.32667268e-17,  1.00000000e+00,
         4.85722573e-17],
       [ 0.00000000e+00, -1.11022302e-16, -8.32667268e-17,
         1.00000000e+00]])

In [29]:
arr_c = np.ones((1000,1000),order='C')
arr_c    

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [32]:
arr_f = np.ones((1000,1000),order='F')
arr_f

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [36]:
sequence = [1,2,None,4,None,5]
total = 0
for value in sequence:
    if value is None:
        continue#提前进入循环
    total += value
print(total)

12


In [39]:
sequence = [1,2,0,4,6,5,2,1]
total_until_5 = 0
for value in sequence:
    if value == 5:
        break#当满足if条件循环退出
    total_until_5 += value
print(total_until_5)
    

13


In [2]:
import numpy as np
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])